# Generated by Django 4.2.11 on 2024-06-08 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passengers',
            fields=[
                ('id_pas', models.AutoField(primary_key=True, serialize=False)),
                ('fio_p', models.CharField(max_length=255, verbose_name='ФИО Пассажира')),
                ('tep_p', models.CharField(max_length=50, verbose_name='Номер телефона')),
                ('sex_p', models.CharField(max_length=8, verbose_name='Пол')),
                ('pass_category', models.CharField(max_length=50, verbose_name='Категория пасажира')),
                ('dop_inf', models.TextField(blank=True, null=True, verbose_name='Дополнительная информация')),
                ('eks', models.BooleanField(verbose_name='Наличие кардиостимулятора')),
            ],
            options={
                'verbose_name': 'пассажира',
                'verbose_name_plural': 'Пассажиры',
                'db_table': 'Passengers',
            },
        ),
    ]
