# Generated by Django 4.2.11 on 2024-06-08 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passengers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passengers',
            name='id_pas',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
